name = "Lean4Graphsee"
version = "0.1.0"

[[require]]
name = "proofwidgets"
git = "https://github.com/Leon-Wloch/ProofWidgets4.git"
rev = "main"

[[lean_lib]]
name = "Lean4Graphsee"

[[lean_lib]]
name = "Graphsee"
